apiVersion: v1
kind: ConfigMap

metadata:
  name: myapi-prod-config
  namespace: myapi-prod

data:
  ConnectionStrings__DefaultConnection: "Server=host.docker.internal,1433;Database=DemoDB;User Id=sa;Password=Password123!;TrustServerCertificate=True;"