apiVersion: v1
kind: Namespace
metadata:
  name: myapi-stage
  labels:
    app: myapi
    environment: stage

---
apiVersion: v1
kind: Namespace
metadata:
  name: myapi-prod
  labels:
    app: myapi
    environment: production